"""Initial migration.

Revision ID: 3b9a486ac548
Revises: 
Create Date: 2023-08-16 09:56:34.869186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b9a486ac548'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxi_ride',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pickup_location', sa.String(length=128), nullable=True),
    sa.Column('dropoff_location', sa.String(length=128), nullable=True),
    sa.Column('fare', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taxi_ride')
    # ### end Alembic commands ###
